; ==============================================================================
; CHAOS MOD GTA SA DEFINITIVE EDITION - CONFIGURATION FILE
; Updated by ChaosConfig.exe on 2026-09-27 02:37:19
; ==============================================================================

[SETTINGS]
GtaExePath=C:\Games\Grand Theft Auto San Andreas The Definitive Edition\Gameface\Binaries\Win64\SanAndreas.exe

[TRIGGER]
Active=None

[LICENSE]
HWID=XMD-FC27-388F-41BA-89DA
Key=XUM-HTUT-WTK6-QWE5
Status=Active
Token=27204216152F7D45A44D555ACBEA7B51DD6F01109ED3EC72F9699AC583CFC1D9

[SPAWN_CAR]
Enabled=1
Hotkey=22577
Name=Spawn Mobil Sport Random

[SPAWN_MOTO_GP]
Enabled=1
Hotkey=49
Name=Spawn NRG-500

[SPAWN_ATV]
Enabled=1
Hotkey=0
Name=Spawn Quad / ATV

[SPAWN_VORTEX]
Enabled=1
Hotkey=0
Name=Spawn Vortex Hovercraft

[SERUDUK_TRUCK]
Enabled=1
Hotkey=0
Name=Linerunner Tabrak CJ

[SERUDUK_TANK]
Enabled=1
Hotkey=0
Name=Tank Rhino Tabrak CJ

[MOBIL_DIDEREK]
Enabled=1
Hotkey=0
Name=Mobil Derek Flatbed / Amparan (Angkut Mobil)

[CHANGE_VEHICLE]
Enabled=1
Hotkey=0
Name=Ganti Kendaraan Acak (Instant 'Y')

[CAR_JUMP]
Enabled=1
Hotkey=0
Name=Super Car Jump (Bunny Hop)

[REPAIR_VEHICLE]
Enabled=1
Hotkey=0
Name=Perbaiki Mobil 100% (Visual & Mesin)

[POP_TIRES]
Enabled=1
Hotkey=0
Name=Pecahkan Semua Ban Mobil

[SPAWN_HUNTER]
Enabled=1
Hotkey=0
Name=Spawn Helikopter Tempur Hunter

[SPAWN_HYDRA]
Enabled=1
Hotkey=0
Name=Spawn Jet Tempur Militer Hydra

[SPAWN_MONSTER]
Enabled=1
Hotkey=0
Name=Spawn Monster Truck

[HEAVY_VEHICLE]
Enabled=1
Hotkey=0
Name=Mobil Kebal & Berat Tank (Tabrak Mental)

[MOBIL_KEBAL]
Enabled=1
Hotkey=0
Name=Mobil Kebal (God Mode Mobil)

[NOS]
Enabled=1
Hotkey=0
Name=NOS Maju (Boost Forward)

[NOS_BACKWARD]
Enabled=1
Hotkey=0
Name=NOS Mundur (Boost Backward)

[SPIN_CAR]
Enabled=1
Hotkey=0
Name=Mobil Muter Gasing (Beyblade)

[MOBIL_KELANGIT]
Enabled=1
Hotkey=0
Name=Melontar ke Langit + Parasut

[EXIT_VEHICLE]
Enabled=1
Hotkey=0
Name=Eject Keluar Kendaraan

[BOOST_SPEED]
Enabled=1
Hotkey=0
Name=Boost Kecepatan / Dash

[TOGGLE_KEBAL]
Enabled=1
Hotkey=0
Name=Toggle Kebal (God Mode)

[TERJUN_PAYUNG]
Enabled=1
Hotkey=0
Name=Teleport Langit + Parasut

[JETPACK]
Enabled=1
Hotkey=0
Name=Beri Jetpack

[SUPER_JUMP]
Enabled=1
Hotkey=0
Name=Konser Boyband CJ + 5 Dancer (Joget Boyband)

[SLOW_MOTION]
Enabled=1
Hotkey=0
Name=Matrix Bullet Time (Slow Motion 0.35x)

[FAST_MOTION]
Enabled=1
Hotkey=0
Name=Sonic Fast Speed (Kecepatan 2.0x)

[NIGHT_VISION]
Enabled=1
Hotkey=0
Name=Toggle Night Vision (Penglihatan Malam)

[THERMAL_VISION]
Enabled=1
Hotkey=0
Name=Toggle Thermal / Infrared Vision

[SPAWN_BODYGUARD]
Enabled=1
Hotkey=0
Name=Spawn Pengawal Minigun Grove Street

[KURUS]
Enabled=1
Hotkey=0
Name=CJ Kurus

[GEMUK]
Enabled=1
Hotkey=0
Name=CJ Gemuk

[UBAH_BAJU_CELANA]
Enabled=1
Hotkey=51
Name=Ubah Pakaian & Postur Acak

[MEDKIT_DUIT]
Enabled=1
Hotkey=0
Name=Full Darah, Armor & Perbaiki Mobil + Duit $250k

[IMUNE_MINUS_1]
Enabled=1
Hotkey=0
Name=Darah Kritis (1 HP)

[CJ_DEATH]
Enabled=1
Hotkey=0
Name=Instant Wasted (Bunuh Diri)

[TELEPORT_RANDOM]
Enabled=1
Hotkey=262194
Name=Teleport Acak (5 Lokasi)

[WEAPON_SET_NINJA]
Enabled=1
Hotkey=0
Name=Ninja Samurai Set (Katana + Smoke + Knife)

[REMOVE_CURRENT_WEAPON]
Enabled=1
Hotkey=0
Name=Hapus Semua Senjata

[WEAPON_SET_1]
Enabled=1
Hotkey=0
Name=Weapon Set 1 (Pistol, Shotgun, Uzi)

[WEAPON_SET_2]
Enabled=1
Hotkey=0
Name=Weapon Set 2 (Deagle, Spas, MP5, AK)

[WEAPON_SET_3]
Enabled=1
Hotkey=0
Name=Weapon Set 3 (M4, Sniper, Rocket)

[WEAPON_SET_4]
Enabled=1
Hotkey=0
Name=Weapon Set 4 (Minigun 500 Ammo)

[RANDOM_WEAPON_SET]
Enabled=1
Hotkey=0
Name=Senjata Acak Tunggal

[GIVE_PARACHUTE]
Enabled=1
Hotkey=0
Name=Beri Parasut

[NPC_PEMUKUL]
Enabled=1
Hotkey=0
Name=Spawn Musuh Pemukul

[NPC_OP]
Enabled=1
Hotkey=0
Name=Spawn Musuh Senapan M4

[EXPLODE_CJ]
Enabled=1
Hotkey=0
Name=Ledakan di Badan CJ

[CJ_KEBAKAR]
Enabled=1
Hotkey=0
Name=CJ Terbakar Api

[METEOR]
Enabled=1
Hotkey=0
Name=Hujan Meteor

[WEATHER_THUNDER]
Enabled=1
Hotkey=0
Name=Ganti Cuaca Acak (Random Weather)

[WEATHER_SANDSTORM]
Enabled=1
Hotkey=0
Name=Cuaca Badai Pasir Gurun

[WEATHER_SUNNY]
Enabled=1
Hotkey=0
Name=Cuaca Cerah Paradise

[BINTANG_0]
Enabled=1
Hotkey=0
Name=Hapus Bintang Wanted Level

[BINTANG_6]
Enabled=1
Hotkey=0
Name=Set Wanted Level Bintang 6

[SPAWN_POHON]
Enabled=1
Hotkey=0
Name=Spawn Pohon Raksasa (Z-Fix)

[SPAWN_RAMP]
Enabled=1
Hotkey=0
Name=Spawn Stunt Jump Ramp

[SPAWN_RUMAH]
Enabled=1
Hotkey=0
Name=Spawn Rumah Boss (Rumah Acak)

[BLACK_HOLE]
Enabled=1
Hotkey=0
Name=Pusaran Gravitasi Black Hole (Menyedot CJ & Mobil)

[CAR_RAIN]
Enabled=1
Hotkey=0
Name=Hujan Kardus

[CJ_CLONE_ARMY]
Enabled=1
Hotkey=0
Name=Pasukan CJ Kembar Bersenjata (Minigun, RPG, Shotgun)

